const fs = require('fs');
const path = require('path');

const rawPath = path.join(__dirname, '../src/lib/raw_subway_data.json');
const outPath = path.join(__dirname, '../src/lib/subway_coordinates.ts');

const rawData = JSON.parse(fs.readFileSync(rawPath, 'utf8'));

const coords = {};
rawData.forEach(station => {
    if (station.gtfs_stop_id && station.gtfs_latitude && station.gtfs_longitude) {
        coords[station.gtfs_stop_id] = {
            lat: parseFloat(station.gtfs_latitude),
            lon: parseFloat(station.gtfs_longitude)
        };
    }
});

const fileContent = `// Auto-generated by scripts/generate_subway_coords.js
export const SUBWAY_COORDINATES: Record<string, {lat: number, lon: number}> = ${JSON.stringify(coords, null, 2)};
`;

fs.writeFileSync(outPath, fileContent);
console.log(`Generated coordinates for ${Object.keys(coords).length} subway stations.`);
